list:
    1:
        tag:
            动作片: 动作片
            喜剧片: 喜剧片
            爱情片: 爱情片
            科幻片: 科幻片
            恐怖片: 恐怖片
            犯罪片: 犯罪片
            战争片: 战争片
            动画片: 动画片
            剧情片: 剧情片
            悬疑片: 悬疑片
            奇幻片: 奇幻片
        area:
            大陆:  大陆
            香港:  香港
            台湾:  台湾
            美国:  美国
            法国:  法国
            英国:  英国
            日本:  日本
            韩国:  韩国
            德国:  德国
            泰国:  泰国
            印度:  印度
            意大利: 意大利
            西班牙: 西班牙
            加拿大: 加拿大
            其他:  其他
        year:
            2004: 2004
            2005: 2005
            2006: 2006
            2007: 2007
            2008: 2008
            2009: 2009
            2010: 2010
            2011: 2011
            2012: 2012
            2013: 2013
            2014: 2014
            2015: 2015
            2016: 2016
            2017: 2017
            2018: 2018
            2019: 2019
            2020: 2020
            2021: 2021
            2022: 2022
    4:
        tag:
            国产动漫: 国产动漫
            日本动漫: 日本动漫
            欧美动漫: 欧美动漫
            海外动漫: 海外动漫
        area:
            大陆:  大陆
            香港:  香港
            台湾:  台湾
            美国:  美国
            法国:  法国
            英国:  英国
            日本:  日本
            韩国:  韩国
            德国:  德国
            泰国:  泰国
            意大利: 意大利
            西班牙: 西班牙
            加拿大: 加拿大
            其他:  其他
        year:
            2004: 2004
            2005: 2005
            2006: 2006
            2007: 2007
            2008: 2008
            2009: 2009
            2010: 2010
            2011: 2011
            2012: 2012
            2013: 2013
            2014: 2014
            2015: 2015
            2016: 2016
            2017: 2017
            2018: 2018
            2019: 2019
            2020: 2020
            2021: 2021
            2022: 2022
    2:
        tag:
            国产剧: 国产剧
            欧美剧: 欧美剧
            韩国剧: 香港剧
            日本剧: 海外剧
            台湾剧: 台湾剧
            泰剧:  泰剧
        area:
            内地:  内地
            美国:  美国
            韩国:  韩国
            香港:  香港
            台湾:  台湾
            日本:  日本
            泰国:  泰国
            英国:  英国
            新加坡: 新加坡
            其他:  其他
        year:
            2004: 2004
            2005: 2005
            2006: 2006
            2007: 2007
            2008: 2008
            2009: 2009
            2010: 2010
            2011: 2011
            2012: 2012
            2013: 2013
            2014: 2014
            2015: 2015
            2016: 2016
            2017: 2017
            2018: 2018
            2019: 2019
            2020: 2020
            2021: 2021
            2022: 2022
    3:
        tag:
            大陆:   大陆
            日韩综艺: 日韩综艺
            港台综艺: 港台综艺
            欧美综艺: 欧美综艺
        area:
            内地: 内地
            港台: 港台
            日韩: 日韩
            欧美: 欧美
        year:
            2004: 2004
            2005: 2005
            2006: 2006
            2007: 2007
            2008: 2008
            2009: 2009
            2010: 2010
            2011: 2011
            2012: 2012
            2013: 2013
            2014: 2014
            2015: 2015
            2016: 2016
            2017: 2017
            2018: 2018
            2019: 2019
            2020: 2020
            2021: 2021
            2022: 2022
class:
    1: 电影
    2: 电视剧
    3: 综艺
    4: 动漫