# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    router.request_context.scheme: 'https'
    router.request_context.host: 'www.hilaiya.com'
    asset.request_context.secure: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\DocumentRepository\:
        resource: '../src/DocumentRepository/*'
    Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler:
        arguments:
            - '@doctrine_mongodb.odm.default_connection'
            - { database: 'customer_session', collection: 'guid'}
#    app.sitemap.blog_post_subscriber:
#        class: App\EventListener\SitemapSubscriber
#        arguments:
#            - App\DocumentRepository\ListsRepository
#        tags:
#            - { name: "kernel.event_subscriber", priority: 100 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
